name: Post welcome comment
on: 
  pull_request:
    types:
      - opened
permissions:
  # Gives permissions to write to pull requests
  pull-requests: write

jobs:
  build:
    name: Post welcome comment
    runs-on: ubuntu-latest
    steps:
      - run: gh pr comment $PR_URL --body "Welcome to the repository!"
        env:
          # Access token generated when the workflow is run
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          # PR Url from the event
          PR_URL: ${{ github.event.pull_request.html_url }}
